### ISSUE TITLE
handle page_build github messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#188]
like these two:

- https://apps.fedoraproject.org/datagrepper/id?id=2015-d6548647-adac-46e4-bdd3-ad8c1d7b1d8c&is_raw=true&size=extra-large
- https://apps.fedoraproject.org/datagrepper/id?id=2015-9515cde4-0804-48a0-ab52-7ff7dc0507b5&is_raw=true&size=extra-large

**Comment by Ghost-script** [comment]
Hi, i would like to work on this enhancement. Can you please guide me through the process? I have already followed the steps in readme for installing dependencies and running tests.

**Comment by ralphbean** [comment]
oh, cool!  Thanks @Ghost-script.

How's this sound?

- take one of those messages and copy the json body of it (from one of the links up there).
- open ``fedmsg_meta_fedora_infrastructure/tests/github.py`` and add a new test by copying one of the existing ones.
- For the ``msg = {....`` part, copy in the json body of the message you copied from datagrepper in step 1.
- Fill out the ``expected_...`` fields with some reasonable values you think the message should have.  (You get to decide!)
- Then run the tests with ``PYTHONPATH=. nosetests -x fedmsg_meta_fedora_infrastructure/tests/github.py``.  They should fail, since you added new expectations to the test without any implementation yet.  This is good.
- Then, open up ``fedmsg_meta_fedora_infrastructure/github.py`` and start implementing.  Add things until you can get your test to pass.
- Once you get all those tests passing, submit a pull-request.  One of us will review the changes and perhaps have a discussion about it before eventually merging it.

**Comment by Ghost-script** [comment]
Hello @ralphbean , 
Before i start. Two tests are failing when i run tests. Is it okay for these tests to fail?

======================================================================
FAIL: test_long_form (fedmsg_meta_fedora_infrastructure.tests.TestKojiBuildStateChangeComplete)
Does fedmsg.meta produce the expected long form text?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subho/work/fedora-infra/fedmsg_meta_fedora_infrastructure/env/lib/python2.7/site-packages/fedmsg-0.12.2-py2.7.egg/fedmsg/tests/test_meta.py", line 48, in inner
    return func(self)
  File "/home/subho/work/fedora-infra/fedmsg_meta_fedora_infrastructure/env/lib/python2.7/site-packages/fedmsg-0.12.2-py2.7.egg/fedmsg/tests/test_meta.py", line 190, in test_long_form
    self.assertMultiLineEqual(actual_long_form, self.expected_long_form)
AssertionError: u"kevin's ansible-1.8.3-1.el7 completed" != "kevin's ansible-1.8.3-1.el7 completed\n\nPackage:    ansible-1.8.3-1.el7\nStatu [truncated]...
- kevin's ansible-1.8.3-1.el7 completed
+ kevin's ansible-1.8.3-1.el7 completed

Package:    ansible-1.8.3-1.el7
Status:     complete
Built by:   kevin
ID:         612324
Started:    Tue, 17 Feb 2015 23:39:49 UTC
Finished:   Tue, 17 Feb 2015 23:41:56 UTC

Closed tasks:
-------------
Task 8973154 on arm02-builder15.arm.fedoraproject.org
Task Type: build (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=8973154

Task 8973158 on buildhw-11.phx2.fedoraproject.org
Task Type: buildSRPMFromSCM (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=8973158
logs:
  https://kojipkgs.fedoraproject.org/work/tasks/3158/8973158/root.log
  https://kojipkgs.fedoraproject.org/work/tasks/3158/8973158/build.log
  https://kojipkgs.fedoraproject.org/work/tasks/3158/8973158/state.log
srpm:
  https://kojipkgs.fedoraproject.org/work/tasks/3158/8973158/ansible-1.8.3-1.el7.src.rpm

Task 8973189 on buildhw-04.phx2.fedoraproject.org
Task Type: buildArch (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=8973189
logs:
  https://kojipkgs.fedoraproject.org/work/tasks/3189/8973189/root.log
  https://kojipkgs.fedoraproject.org/work/tasks/3189/8973189/build.log
  https://kojipkgs.fedoraproject.org/work/tasks/3189/8973189/state.log
rpms:
  https://kojipkgs.fedoraproject.org/work/tasks/3189/8973189/ansible-1.8.3-1.el7.noarch.rpm
srpms:
  https://kojipkgs.fedoraproject.org/work/tasks/3189/8973189/ansible-1.8.3-1.el7.src.rpm

Task 8973199 on arm02-builder15.arm.fedoraproject.org
Task Type: tagBuild (noarch)
Link: https://koji.fedoraproject.org/koji/taskinfo?taskID=8973199



======================================================================
FAIL: test_long_form (fedmsg_meta_fedora_infrastructure.tests.TestKojiBuildStateChangeFail)
Does fedmsg.meta produce the expected long form text?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/subho/work/fedora-infra/fedmsg_meta_fedora_infrastructure/env/lib/python2.7/site-packages/fedmsg-0.12.2-py2.7.egg/fedmsg/tests/test_meta.py", line 48, in inner
    return func(self)
  File "/home/subho/work/fedora-infra/fedmsg_meta_fedora_infrastructure/env/lib/python2.7/site-packages/fedmsg-0.12.2-py2.7.egg/fedmsg/tests/test_meta.py", line 190, in test_long_form
    self.assertMultiLineEqual(actual_long_form, self.expected_long_form)
AssertionError: u"sharkcz's 64tass-1.51.727-1.fc22 failed to build (s390)" != "sharkcz's 64tass-1.51.727-1.fc22 failed to build (s390)\n\nPackage:    64tass-1 [truncated]...
- sharkcz's 64tass-1.51.727-1.fc22 failed to build (s390)
+ sharkcz's 64tass-1.51.727-1.fc22 failed to build (s390)

Package:    64tass-1.51.727-1.fc22
Status:     failed
Built by:   sharkcz
ID:         288888
Started:    Tue, 24 Feb 2015 14:19:09 UTC
Finished:   Tue, 24 Feb 2015 14:19:46 UTC

Closed tasks:
-------------
Task 1739950 on fedora1.s390.bos.redhat.com
Task Type: build (noarch)
Link: http://s390.koji.fedoraproject.org/koji/taskinfo?taskID=1739950

could not init mock buildroot, mock exited with status 1; see build.log for more information



----------------------------------------------------------------------
Ran 3354 tests in 120.111s

FAILED (failures=2, skipped=1478)

**Comment by ralphbean** [comment]
> Is it okay for these tests to fail?

Odd.  Yes, it's okay that they fail for the purposes of fixing this other ticket (but I'd like to fix them on their own longer-term).
