### ISSUE TITLE
Get icons for the fedimg messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#218]
They currently look pretty naked:  https://apps.fedoraproject.org/datagrepper/raw?category=fedimg&delta=3600000  compared with https://apps.fedoraproject.org/datagrepper/raw?category=copr&delta=3600000

We could ask the design-team to make an icon for fedimg, or re-use an existing rel-eng one if we have one somewhere.

**Comment by oddshocks** [comment]
Maybe we could just use the Fedora Cloud logo? One of the lil' guys shaped like Fedora logos, but ~*~~clouds~*~*~?
![cloudsig-banner](https://cloud.githubusercontent.com/assets/1376599/6542777/3d1074ca-c4b9-11e4-9512-0cd4879e4103.png)
Could even tweak it somehow for Fedimg.

**Comment by oddshocks** [comment]
Wait, I got it. And hear me out here: what if we -- wait for it -- what if we put a cloud logo inSIDE of a cloud logo? Eh? Right? It's good, right? "Fedimg: it's the Cloud... for your Cloud"

**Comment by ralphbean** [comment]
Oooo.. or are we allowed to re-use this thing?

![](https://getfedora.org/static/images/logo-color-cloud.png)

**Comment by oddshocks** [comment]
@ralphbean I like that idea even better. I could ping design-team, they might know what we can use.

**Comment by oddshocks** [comment]
@ralphbean , I spoke with Mizmo and she suggested the un-textured icon for this use case. She produced the below for us. I vote we add it in.
![fedora_cloud_48_48](https://cloud.githubusercontent.com/assets/1376599/6583015/70b33be8-c71e-11e4-9ee4-81691f997c64.png)

**Comment by ralphbean** [comment]
Sounds good.  We'll need to host it at https://apps.fedoraproject.org/img/icons/ with most of the others and then link to it from there.

**Comment by ralphbean** [comment]
Fixed in 77f83a32964258644930e9a8734cab9299debbb2
