### ISSUE TITLE
Use the openid libravatar first for git.receive messages if possible

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#220]
We currently use the libravatar based on the email address of the committer for ``git.push`` messages.

*Everywhere* else we use the libravatar based on the user's FAS openid string (``http://FASUSERNAME.id.fedoraproject.org/``).

It would be great if we could bring those ``git.receive`` messages in-line with the others and use the openid libravatar first where possible.  If for some reason a message doesn't have a FAS username associated with it, we could fall back to using the email-based libravatar url.

**Comment by Ghost-script** [comment]
@ralphbean thanks. :) Working on this.

**Comment by ralphbean** [comment]
Well, the code right here will need to be changed:  https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/scm.py#L35-L37

**Comment by ralphbean** [comment]
And this test:  https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/tests/scm.py#L44-L47

Will need to be changed to this link:  https://seccdn.libravatar.org/avatar/9c9f7784935381befc302fe3c814f9136e7a33953d0318761669b8643f4df55c?s=64&d=retro  (or something like it)

**Comment by ralphbean** [comment]
Wait.. that last part's not true.  Some tests will still need to have the old email-based image url while others will need to have the new openid-based image url.  (This is because some old messages do not have a FAS username in them and we don't have enough information to know how to create an openid without a fas username).

**Comment by Ghost-script** [comment]
@ralphbean  i wrote the code. But obviously the test message doesn't have any FAS username. I am currently following this example.

https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/fedmsg_meta_fedora_infrastructure/tests/__init__.py#L539#L571

so first looking for msg['msg']['commit']['username'] if not available returning the email based libravatar url.

If the above example is acceptable then i can add another testcase to the tests/scm.py file fo modern FAS based libravatar url.

**Comment by ralphbean** [comment]
Yes!  That sounds good :)
