### ISSUE TITLE
fedmsg error log notifs-backend01: hottness.py: KeyError: 'packages'

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/fedmsg_meta_fedora_infrastructure#256]
```
  File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/hotness.py", line 226, in packages
    pkg['package_name'] for pkg in original['message']['packages']
KeyError: 'packages'
```
:mailbox_with_mail: `Purge 2135 deleted messages? ([yes]/no):`

**Comment by ralphbean** [comment]
Pretty sure this is fixed in c7f8dfae32c491d8d06077d7e3cafc96454f9e96 but just hasn't been deployed yet.  I was waiting for the freeze to be up.  It lifted today so I'll try to roll it out tomorrow.
