### ISSUE TITLE
unhandled pagure message type

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#277]
I saw [this one](https://apps.fedoraproject.org/datagrepper/id?id=2015-9ab3ba70-02aa-4034-a532-8791696165fd&is_raw=true&size=extra-large) this morning.

**Comment by Ghost-script** [comment]
@ralphbean , While running the tests for pagure.py , The tests "expected_icon" and "expected_link" seems to be failing for most. Here is the test output. http://ur1.ca/nbau8 , i am on `develop` branch

**Comment by ralphbean** [comment]
@Ghost-script it looks like everything is failing, not just those two checks.  Can you verify that you have the package installed with ``python setup.py develop`` as described in the README?

**Comment by Ghost-script** [comment]
@ralphbean , thanks  :+1:, that solved it :) i was using an old virtualenv.  Writing the tests right away.

**Comment by Ghost-script** [comment]
Fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/301
