### ISSUE TITLE
Add a long_form implementation for badges emails

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#278]
They should include a *description* of the badge, not just the name and link.  And maybe a link to the criteria too?

This idea was originally filed here:  https://fedorahosted.org/fedora-badges/ticket/382

**Comment by ralphbean** [comment]
For anyone interested in working on this, see the long_form implementation for "bodhi comments" as an example.

**Comment by pranavk** [comment]
Please have a look here, #280

**Comment by ralphbean** [comment]
This is done now thanks to @pranavk.  We just need a new release and to have it deployed to the notifications server.
