### ISSUE TITLE
pagure links could contain anchors

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#279]
for instance, if someone comments on a pagure ticket, we could link to the individual comment instead of just to the top-level ticket.

**Comment by Ghost-script** [comment]
I think this has been fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/commit/b23e242473d749ed7c1256981d2cbce5dea04ab1

**Comment by ralphbean** [comment]
Yup!  Thanks :)
