### ISSUE TITLE
URLs to Copr build logs in email notifications need updating

### ISSUE THREAD

**Issue by danvratil** [fedora-infra/fedmsg_meta_fedora_infrastructure#281]
Hi,

with the last major Copr update there were some changes in the logs which broke the links in email notifications from fedmsg:

1) Copr now compresses the build logs by default, so the URLs should be as follows:

    Build:     https://copr-be.cloud.fedoraproject.org/results/{owner}/{copr}/{chroot}/{pkg}/build.log.gz
    Root:      https://copr-be.cloud.fedoraproject.org/results/{owner}/{copr}/{chroot}/{pkg}/root.log.gz

2) For new coprs, there does not seem to be mockchain.log created anymore and in existing coprs it's not updated, so the link should be removed completely.

3) Finally, in the "Copr" log (`https://copr-be.cloud.fedoraproject.org/results/{owner}/{copr}/{chroot}/build-{build}.log`), the buildID (``{build}``) seems to be zero-padded now to always have 8 characters.

See this link for example of the new logs: https://copr-be.cloud.fedoraproject.org/results/dvratil/qt5/fedora-22-x86_64/

**Comment by ralphbean** [comment]
Confirmed fixed by #298.
