### ISSUE TITLE
Handle github deployment_status messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#291]
Like [this one](https://apps.fedoraproject.org/datagrepper/id?id=2015-2ddc0584-c5ed-49e8-b81c-d021ad7dec40&is_raw=true&size=extra-large).  What even is that?  :new_moon_with_face:

**Comment by Ghost-script** [comment]
Messages from pythonindia repository? :confused:
