### ISSUE TITLE
Handle bodhi.update.edit messages

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#310]
Like [this one](https://apps.fedoraproject.org/datagrepper/id?id=2015-33f2b354-8070-46dc-8361-a00d189394d2&is_raw=true&size=extra-large) which we have never had before.

**Comment by Ghost-script** [comment]
@ralphbean , Working on it.

**Comment by Ghost-script** [comment]
@ralphbean : shouldn't there be `mediawiki` mentioned as build package and title?

**Comment by ralphbean** [comment]
Now that I look more closely at it, I think this might be a bad example.

The update has no ``alias`` to uniquely identify it.. and the list of ``builds`` is ``[]``.  The ``title`` is ``""``.  This may have been a *buggy* message from bodhi2 shortly after the rollout.

**Comment by ralphbean** [comment]
Yeah, confirmed.  These messages are handled presently.
