### ISSUE TITLE
fix hyperkitty mailman3 icon url

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedmsg_meta_fedora_infrastructure#353]
it broke at some point.  see the broken images here:  https://apps.fedoraproject.org/datagrepper/raw?category=mailman

**Comment by Prashant-Surya** [comment]
Can I fix this?

**Comment by ralphbean** [comment]
Yes.  :)  See the broken images here:  https://apps.fedoraproject.org/datagrepper/raw?category=mailman&delta=127800

The broken link is this:  https://www.openhub.net/attachments/37686/mailman_med.png

We just need to find the new hyperkitty logo (a good trustable url for it) and then swap it out for the old one in the code and the test suite in this repo.

**Comment by Prashant-Surya** [comment]
@ralphbean can I use this link?
https://communityblog.fedoraproject.org/wp-content/uploads/2015/11/hyperkitty_fedora_square.png

**Comment by ralphbean** [comment]
No, unfortunately.  It's a link from a wordpress post so I'm not sure we can trust it being there indefinitely.

How about this one?  https://apps.fedoraproject.org/img/icons/hyperkitty.png

**Comment by pypingou** [comment]
Fixed in https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/pull/388
