### ISSUE TITLE
allow filtering on failed or success taskotron tasks

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedmsg_meta_fedora_infrastructure#356]
Right now there's only: 

New taskotron task result
Particular taskotron task 

It would be nice to be able to filter and only get notified on 'failed' taskotron tasks.

**Comment by kparal** [comment]
We added more rules recently:
https://github.com/fedora-infra/fmn.rules/pull/68
They just need to get deployed.

Also, we want to set up some reasonable taskotron filter by default:
https://github.com/fedora-infra/fmn.lib/pull/58
That's still not resolved yet, sorry. We started sending out messages before we actually had FMN rules and filters in place :-/

**Comment by kparal** [comment]
The changes are now deployed, I believe this ticket can now be closed (however I can't do that).
