### ISSUE TITLE
Add support for namespaces in the git messages

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fedmsg_meta_fedora_infrastructure#380]
When processing messages such as: https://apps.stg.fedoraproject.org/datagrepper/id?id=2016-3a1b35ee-4b2b-420e-8175-40cc42b516f0&is_raw=true&size=extra-large

the link returned does not take into account the namespace when pointing to cgit, we should fix this.

**Comment by ralphbean** [comment]
I think this may be fixed by #378.

**Comment by pypingou** [comment]
Indeed thanks for reminding me of it :)
