### ISSUE TITLE
Fix up the CI and drop Python 2.6

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fedmsg_meta_fedora_infrastructure#442]
CI is failing on 2.6 and isn't testing on Python 3. We should drop Python 2.6 (as our deps no longer support it, including fedmsg) and add Python 3.

**Comment by hugovk** [comment]
Can this be closed? 

Travis is running on 2.7 and 3.6: 

https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/blob/develop/.travis.yml

**Comment by jeremycline** [comment]
Yup, looks like it got fixed in #451, thanks!
