### ISSUE TITLE
compose.* link processing is kind of a mess, what should we do?

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/fedmsg_meta_fedora_infrastructure#458]
So I've been working on the `compose.*` messages lately. I just started thinking about what to do with the `link` method, for providing some kinda URL associated with a message. I'm not sure what's the best way to go.

What's there right now is very inadequate and is going to give wrong/nonsensical links for many messages. I could go into exhaustive detail, but basically it's clear that no-one's really thought about the links for all the various different types of compose we have now. (You can just look at the links the tests expect to see that many of them are just...wrong).

I'm filing this ticket instead of sending a PR because I can kinda see two choices, here, and I'm not sure which is best.

Option 1 is to write a really complex processor - it'd be several dozen lines, at least, maybe more, and it'd duplicate quite a bit of knowledge with [fedfind](https://pagure.io/fedora-qa/fedfind) , unless we added a dependency on fedfind which would be a whole other approach - that would really give the 'best' URL for each message. There's quite a lot to figure out if we do this: when do we give the URL to the compose's location under https://kojipkgs.fedoraproject.org/compose/ ? When do we give the URL to the location the compose gets synced to in the mirror system, for composes that get synced? What do we do for cases where we can't know either of those locations? What do we do about the fact that composes get garbage collected, so even the 'correct' locations for most composes over two weeks old won't exist any more?

Option 2 is to essentially give up and decide Option 1 is too much work for too little return, and just do this (or something similar):

    def link(self, msg, **config):
        return "https://kojipkgs.fedoraproject.org/compose/"

I'm not sure which is the best choice, so I thought I'd file a ticket and see what folks think. So...what do you think? @ralphbean @ausil @mohanboddu @pypingou

**Comment by AdamWill** [comment]
It occurs to me that it may be easier to have the scripts emit a 'location' key in the message dict, that the processor could use as the URL for the message...and if the message doesn't have a 'location' key, just give the generic location...that's a third option, let's say.

**Comment by pypingou** [comment]
> It occurs to me that it may be easier to have the scripts emit a 'location' key in the message dict

This is likely an easier idea which would solve quite some problems, maybe even for fedfind itself :)

**Comment by AdamWill** [comment]
"This is likely an easier idea which would solve quite some problems, maybe even for fedfind itself :)"

It wouldn't help fedfind at all as it happens (mumble mumble technical reasons mumble), but it could possibly be the way to go here. I'll have a look at the scripts and see how easy it'd be...

**Comment by AdamWill** [comment]
This is done now, by #462 (and relevant PRs / commits to [pungi-fedora](https://pagure.io/pungi-fedora)). It appears to also be in production. Whee!
